name: RoutedCargo
version: '${project.version}'
main: subude.gg.RoutedCargo
api-version: '1.18'
load: STARTUP
authors: [subude, Mazayka]
description: Обещания надо исполнять
commands:
  cargo:
    description: Управление Маршруточным грузом
    usage: /cargo <start|stop|status>
    permission: cargo.use
    aliases: [cg]
    permission-message: У вас нет прав на использование этой команды