name: RoutedCargo
version: '1.0'
main: subude.gg.RoutedCargo
api-version: '1.18'
load: STARTUP
authors: [subude, Mazayka]
description: Обещания надо исполнять
commands:
  cartspawn:
    description: Spawn test minecart
  carttp:
    description: Teleport minecart
  cartmove:
    description: Push minecart